### ISSUE TITLE
Feedback on v2

### ISSUE THREAD

**Issue by luisignaciocc** [luisignaciocc/youtube-music-scrobbler#14]
Hey Robert @roos-robert,

As I mentioned a few days ago, I'm working on a version two of this process. I've made some progress, and everything is in this repository: [https://github.com/luisignaciocc/ytmusic-scrobbler-web](https://github.com/luisignaciocc/ytmusic-scrobbler-web). I haven't added the latest changes you made to the original script yet, but I plan to do so later. I'm letting you know in case you want to take a look; maybe you'll notice something that can be improved (I'm not an expert in open source). 

I haven't had much time, so most of it was done quickly with the help of AI tools, so the quality might not be the best, but it has worked so far.

I already have a deployed version in production here: [https://scrobbler.bocono-labs.com/](https://scrobbler.bocono-labs.com/). I haven't been able to validate the application with Google yet, so it's in development mode. If you want to try it, you'll need to send me your email to add you to the testing user list. 

Anyway, whether it's to send some PRs, tell me what's missing in the documentation, or give me general feedback on the process, your input would be very helpful.

**Comment by roos-robert** [comment]
Hey @luisignaciocc and thank you for the update!

I Apologize for the late reply, been a busy few weeks (as always with Midsummer haha). This looks awesome, great job so far on the application! So much better to have this running as a web app and lowering the bar for usage for a lot of people.

I have not had the opportunity to try it out yet, thinking to run it locally since the requirements for signing in with Google are a bit scary at the moment "Give access to manage your playlists and publish comments". I'm not sure how the management for signing in with Google works, but read only access for playlists/history would be optimal for us tin-foil hats 😁

Again, great work so far and it's looking great!
